services:
  smartdock:
    build: .
    container_name: smartdock
    ports:
      - "3000:3000"  # Retour au port standard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MAIN_DOMAIN=localhost
      - API_KEY=your-secure-api-key-here
    restart: unless-stopped
    labels:
      - "smartdock.wakeup=false"
      - "smartdock.autoupdate=true"
    networks:
      - smartdock-network
    user: "root"  # Nécessaire pour accéder au socket Docker

networks:
  smartdock-network:
    driver: bridge
    external: false