services:
  smartdock:
    build: .
    container_name: smartdock
    ports:
      - "9001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MAIN_DOMAIN=localhost
      - API_KEY=your-secure-api-key-here
    restart: unless-stopped
    labels:
      - "smartdock.wakeup=false"
      - "smartdock.autoupdate=true"
    networks:
      - smartdock-network

  caddy:
    image: caddy:2-alpine
    container_name: smartdock-proxy
    ports:
      - "9080:80"
      - "9443:443"
      - "9019:2019"
    command: |
      sh -c 'echo "
      {
          admin :2019
          auto_https off
      }
      
      :80 {
          reverse_proxy smartdock:3000
      }
      
      *.localhost:80 {
          @wakeup not path /api/*
          handle @wakeup {
              reverse_proxy smartdock:3000/api/wakeup/{host}
          }
          reverse_proxy smartdock:3000
      }
      " > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - smartdock
    networks:
      - smartdock-network

networks:
  smartdock-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: