services:
  smartdock:
    build: .
    container_name: smartdock
    ports:
      - "9001:3000"  # Port externe 9001 (très éloigné)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ./caddy/smartdock:/app/caddy/smartdock
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MAIN_DOMAIN=localhost
      - API_KEY=your-secure-api-key-here
    restart: unless-stopped
    labels:
      - "smartdock.wakeup=false"
      - "smartdock.autoupdate=true"
    networks:
      - smartdock-network

  caddy:
    image: caddy:2-alpine
    container_name: smartdock-proxy
    ports:
      - "9080:80"   # Port externe 9080 (très éloigné)
      - "9443:443"  # Port externe 9443 (très éloigné)
      - "9019:2019" # Port admin Caddy sur 9019
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/smartdock:/etc/caddy/smartdock:ro
    restart: unless-stopped
    depends_on:
      - smartdock
    networks:
      - smartdock-network

networks:
  smartdock-network:
    driver: bridge