services:
  smartdock:
    build: .
    container_name: smartdock
    ports:
      - "9001:3000"  # Port externe différent pour éviter le conflit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/app/data
      - ./caddy:/etc/caddy
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MAIN_DOMAIN=localhost
      - API_KEY=your-secure-api-key-here
    restart: unless-stopped
    labels:
      - "smartdock.wakeup=false"
      - "smartdock.autoupdate=true"
    networks:
      - smartdock-network
    user: "root"  # Nécessaire pour accéder au socket Docker

  caddy:
    image: caddy:2-alpine
    container_name: smartdock-proxy
    ports:
      - "9080:80"   # Port HTTP non conflictuel
      - "9443:443"  # Port HTTPS non conflictuel
      - "2019:2019" # Port admin Caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/smartdock:/etc/caddy/smartdock:ro
    restart: unless-stopped
    depends_on:
      - smartdock
    networks:
      - smartdock-network

networks:
  smartdock-network:
    driver: bridge
    external: false